# Generated by Django 3.2 on 2021-05-05 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=100)),
                ('gallery_id', models.IntegerField(blank=True, null=True)),
                ('blog_id', models.IntegerField(blank=True, null=True)),
                ('google_id', models.IntegerField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.location')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(blank=True, null=True)),
                ('first_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_point', to='navigation.points')),
                ('second_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second_point', to='navigation.points')),
                ('shared_with', models.ManyToManyField(related_name='shared_with', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
