# Generated by Django 2.2.10 on 2021-07-06 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlocation',
            old_name='user_lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='userlocation',
            old_name='user_lon',
            new_name='lon',
        ),
        migrations.RemoveField(
            model_name='userlocation',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='routes',
            name='shared_with',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
