# Generated by Django 3.2 on 2021-05-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210409_1217'),
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='shared_with',
            field=models.ManyToManyField(to='accounts.UserProfile'),
        ),
    ]
