# Generated by Django 3.2 on 2021-05-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210409_1217'),
        ('navigation', '0002_auto_20210505_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
