# Generated by Django 2.2 on 2021-04-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationTry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SocialTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_description_text',
            new_name='profile_bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_date_of_birth',
            field=models.DateField(default=None, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default=None, max_length=1, verbose_name='Gender'),
        ),
    ]
