# Generated by Django 2.2 on 2021-04-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210407_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_date_of_birth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_phone_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_gender',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=250, verbose_name='Profile Description'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=None, verbose_name='Profile Photo'),
        ),
    ]
