# Generated by Django 2.2 on 2021-06-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210601_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationTry',
        ),
    ]
