# Generated by Django 2.2 on 2021-06-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_registrationtry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauthcredentials',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userauthcredentials',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='userauthcredentials',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='userauthcredentials',
            name='updated_on',
        ),
    ]
