# Generated by Django 2.2 on 2021-06-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210601_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthcredentials',
            name='google_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userauthcredentials',
            name='google_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userauthcredentials',
            name='google_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
