# Generated by Django 2.2 on 2021-06-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210607_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthcredentials',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
