# Generated by Django 2.2 on 2021-06-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210607_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_on',
        ),
    ]
