# Generated by Django 2.2 on 2021-04-07 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('user_ratings', models.FloatField(blank=True, null=True)),
                ('num_rated', models.IntegerField(blank=True, null=True)),
                ('comparable', models.BooleanField(default=True)),
                ('liked', models.BooleanField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.DecimalField(decimal_places=3, max_digits=7)),
                ('first_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_place', to='recommendations.Place')),
                ('second_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_place', to='recommendations.Place')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('gallery_id', models.IntegerField(blank=True, null=True)),
                ('blog_id', models.IntegerField(blank=True, null=True)),
                ('google_id', models.IntegerField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.Place')),
            ],
        ),
    ]
