# Generated by Django 2.2 on 2021-04-14 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarity',
            name='first_place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_place', to='recommendations.Place'),
        ),
        migrations.AlterField(
            model_name='similarity',
            name='second_place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second_place', to='recommendations.Place'),
        ),
    ]
