# Generated by Django 3.2 on 2021-04-28 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0002_auto_20210411_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinelink',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_onlinelink_created_by', to=settings.AUTH_USER_MODEL, verbose_name='who created'),
        ),
        migrations.AddField(
            model_name='onlinelink',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='when created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlinelink',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_onlinelink_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='when updated'),
        ),
        migrations.AddField(
            model_name='onlinelink',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='when updated'),
        ),
        migrations.AddField(
            model_name='place',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_place_created_by', to=settings.AUTH_USER_MODEL, verbose_name='who created'),
        ),
        migrations.AddField(
            model_name='place',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='when created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_place_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='when updated'),
        ),
        migrations.AddField(
            model_name='place',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='when updated'),
        ),
        migrations.AddField(
            model_name='similarity',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_similarity_created_by', to=settings.AUTH_USER_MODEL, verbose_name='who created'),
        ),
        migrations.AddField(
            model_name='similarity',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='when created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='similarity',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_similarity_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='when updated'),
        ),
        migrations.AddField(
            model_name='similarity',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='when updated'),
        ),
    ]
