# Generated by Django 2.2 on 2021-04-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_auto_20210414_1424'),
        ('recommendations', '0002_auto_20210411_1208'),
    ]

    operations = [
    ]
