# Generated by Django 3.2 on 2021-04-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210409_1217'),
        ('recommendations', '0003_auto_20210428_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
