# Generated by Django 2.2 on 2021-05-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_alter_onlinelink_user_id'),
        ('recommendations', '0003_merge_20210415_0908'),
    ]

    operations = [
    ]
