# Generated by Django 2.2 on 2021-05-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0008_alter_place_userprofile'),
        ('recommendations', '0006_merge_20210505_1645'),
    ]

    operations = [
    ]
