# Generated by Django 2.2 on 2021-05-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_merge_20210415_0908'),
        ('recommendations', '0008_alter_place_userprofile'),
    ]

    operations = [
    ]
