# Generated by Django 2.2 on 2021-05-23 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistic_statistic_created_by', to=settings.AUTH_USER_MODEL, verbose_name='who created'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='when created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistic',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistic_statistic_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='when updated'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='when updated'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
