# Generated by Django 3.2 on 2021-05-26 13:06

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_auto_20210523_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='action',
            field=jsonfield.fields.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='statistic',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 26)),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='statistic',
            unique_together={('date', 'object_id')},
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='month',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='week',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='year',
        ),
    ]
