# Generated by Django 3.2 on 2021-05-26 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_auto_20210526_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 26, 13, 7, 54, 248085, tzinfo=utc)),
        ),
    ]
