# Generated by Django 2.2.10 on 2021-06-28 18:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0006_auto_20210526_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='action',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='statistic',
            unique_together=set(),
        ),
    ]
