# Generated by Django 2.2 on 2021-04-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210411_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor_code_old',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(default='', max_length=200, verbose_name='Vendor Code'),
            preserve_default=False,
        ),
    ]
