# Generated by Django 2.2 on 2021-04-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210411_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor_code',
            new_name='vendor_code_old',
        ),
    ]
