# Generated by Django 2.2 on 2021-04-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210411_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.IntegerField(default=0, verbose_name='Vendor Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code_old',
            field=models.CharField(max_length=200, verbose_name='Vendor Code OLD'),
        ),
    ]
