# Generated by Django 2.2 on 2021-05-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210421_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vendor Code'),
        ),
    ]
